teams and achievement page
Hardhat-Enterprises/website pull request #129
Opened 2024-09-08 07:35 UTC by aniruddhvaid1311

team card and achievement section in about page for company high end individuals.

2024-09-13 02:54 UTC, medwut reviewed
Looks good however there are no images for the team members you added is this a mistake ? 
![image](https://github.com/user-attachments/assets/384f18ca-54cd-4b5b-9f2f-2809b27c26e1)

2024-09-16 10:44 UTC, uzairzafarr commented
Hi Anirud, 
I noticed that you've used a placeholder as the image source (https://via.placeholder.com/150). 
Could you please update it with the actual images instead?

Thankyou

2024-11-22 01:44 UTC, s-bonnor requested changes
external image links need to be replaced
bad filename also needs to be fixed

2024-11-22 01:44 UTC, s-bonnor commented on package.json
Why have you created a package.json file?

2024-11-22 01:44 UTC, s-bonnor commented on home/templates/pages/feedback 2 (2).html
i don't believe "feedback 2 (2).html" is the correct filename here

2024-11-22 01:44 UTC, s-bonnor commented on home/templates/pages/about.html
> +            <img src="https://via.placeholder.com/150" alt="John Smith" class="team-photo">
please replace these via.placeholder.com links with in repository images

2024-11-28 02:22 UTC, s-bonnor commented
Closed by request

2024-11-28 02:22 UTC, closed without merging