The pull request updates the navigation bar to enhance functionality, user experience, and design
Hardhat-Enterprises/website pull request #185
Opened 2024-11-26 17:08 UTC by Alimumtaz123

Key changes include:
**Improved Layout**: Updated the structure to ensure better responsiveness across devices.

 Styling Enhancements:

-  Optimized color scheme for better visibility.

- Added hover effects for a more interactive experience.

Bug Fixes:

- Resolved alignment issues on smaller screens.

- Fixed inconsistencies in padding and margins.

2024-12-03 00:01 UTC, s-bonnor requested changes
Looks good other than the missing dark mode toggle

2024-12-03 00:01 UTC, s-bonnor commented on home/templates/includes/navigation.html
> +      </div> -->
So, the dark mode toggle is sort of important, could you fix that

2024-12-03 20:20 UTC, Alimumtaz123 commented
Dark mode button added

2024-12-03 20:22 UTC, Alimumtaz123 commented
dark mode button added

2024-12-08 06:33 UTC, jbm1412 commented
Current Team Member's work so far:

![Screenshot (1994)](https://github.com/user-attachments/assets/3d5a790e-97b4-47ea-b625-c6b0eef33b31)

2024-12-08 07:20 UTC, s-bonnor requested changes
Looks good except for 2 issues
1. the sign-in and sign-up dropdowns still show up when logged in
2. the sign-in and sign-up dropdowns dont respect dark mode and always have yellow text on a white background

also could you fix the merge conflicts

2024-12-10 04:51 UTC, jbm1412 requested changes
![Screenshot (2032)](https://github.com/user-attachments/assets/bff264d0-0112-4fb3-99e6-46da2f9ba00d)
 
Tested -> Works. Looks Good. Please fix the merge conflicts @Alimumtaz123

2024-12-10 12:28 UTC, Alimumtaz123 commented
merge conflicts solved

2024-12-10 18:21 UTC, jbm1412 commented
![Screenshot (2032)](https://github.com/user-attachments/assets/d2b2ba96-f936-4123-96fa-fafd4694da5d)

Tested -> Works. Looks Good!

2024-12-10 18:21 UTC, jbm1412 approved these changes

2024-12-11 03:44 UTC, s-bonnor requested changes
Cyber Challenges Page is cutoff by the navigation bar
![image](https://github.com/user-attachments/assets/0b8c6cdf-347d-4bf4-b4c4-d6abbd7c7d39)

Search Icon is out of place on the about page
![image](https://github.com/user-attachments/assets/30d89b9b-d2d9-4319-8450-f2ba1f96c5de)

it doesnt seem to be possible to interact with the navigation bar at all in the mobile view (when the page is too narrow)

2024-12-12 07:35 UTC, merged