announcements over home page
Hardhat-Enterprises/website pull request #194
Opened 2024-11-29 21:36 UTC by aniruddhvaid1311

2024-12-03 00:46 UTC, s-bonnor requested changes

2024-12-03 00:46 UTC, s-bonnor commented on home/announcemetnts.html
you seem to have a typo in the file name here

2024-12-03 00:46 UTC, s-bonnor commented on home/templates/pages/about.html
> +    </div>
styling on this modal seems to be messed up in dark mode
text is white on white and its squished
![image](https://github.com/user-attachments/assets/da5630a5-f3a9-4219-85fb-4c970087eaac)

2024-12-03 00:46 UTC, s-bonnor commented on home/templates/pages/newsletter
missing an extension on this filename

2024-12-10 07:12 UTC, s-bonnor requested changes

2024-12-10 07:12 UTC, s-bonnor commented on home/templates/pages/about.html
> +    </div>
styling is still broken in darkmode as of the latest changes

2024-12-10 07:12 UTC, s-bonnor commented on home/templates/pages/feedback 2 (2).html
this filename is still wrong

2024-12-10 07:12 UTC, s-bonnor commented on home/templates/pages/newsletter
still missing an extension

2025-05-22 15:59 UTC, vaqwerty2 commented
Too many errors, and there is already an announcements functionality.

2025-05-22 15:59 UTC, closed without merging