Added google map on contact us page
Hardhat-Enterprises/website pull request #195
Opened 2024-11-29 22:19 UTC by patelgruhi

This is contribution task of me and saumil.
Added google map on contact us page.

After:
![{59C4846B-4568-4935-AAC9-C2B4926D8F30}](https://github.com/user-attachments/assets/0854e2b8-dc75-4505-9583-aff19c327469)

2024-12-03 01:01 UTC, s-bonnor requested changes
Looks good other than the noted issue

2024-12-03 01:01 UTC, s-bonnor commented on home/templates/pages/Contactus.html
> +          ></iframe>
missing CSP for iframe prevents it from loading
![image](https://github.com/user-attachments/assets/3d4b5dd4-709a-4ca8-9e49-590013fe6926)

2024-12-06 11:02 UTC, patelgruhi commented
I have added Googlee reCAPTCHA . As you can look at the below image.
![Uploading {00F89BB5-1EA0-455A-A7DA-91C49896AF37}.png…]()

2024-12-08 01:46 UTC, patelgruhi commented
Added reset button.
![{50CC7AF9-6C13-412E-9A67-A7442C026420}](https://github.com/user-attachments/assets/ab19a178-89fb-4e04-85a0-f48c1b11338e)

2024-12-08 07:26 UTC, s-bonnor approved these changes
Looks good, will be merged in a little bit

2024-12-08 07:50 UTC, merged