Added page visit counter styling and functionality
Hardhat-Enterprises/website pull request #207
Opened 2024-12-02 13:32 UTC by Ericsheoran

- Added a visit counter to the footer section.
- Styled the counter to align with the website's design.
- Implemented functionality to track visits per page using localStorage.

2024-12-07 11:23 UTC, Ericsheoran commented
https://youtu.be/o7cE6cIac5g

2024-12-08 07:52 UTC, jbm1412 requested changes
https://github.com/user-attachments/assets/c46962df-5b59-4bcf-88e2-c750f7f0d023

It's not working, please check your js file and script.

2024-12-08 07:52 UTC, jbm1412 commented on home/templates/pages/index.html
![Screenshot (1996)](https://github.com/user-attachments/assets/78e421a8-4d7f-47be-8e4b-08e944c292ee)

Please fix this issue

2024-12-08 07:52 UTC, jbm1412 commented on home/templates/pages/index.html
Please stick to this template 

![Screenshot (1997)](https://github.com/user-attachments/assets/b0ed2d0d-0d47-46b5-8900-e336ec07b84d)

2024-12-09 13:33 UTC, jbm1412 requested changes
![Screenshot (2023)](https://github.com/user-attachments/assets/2cef79c0-e45e-4e2f-8eb7-2d49aae3348c)

Tested -> Works. Looks Good, but fix the conflicting files

2024-12-09 13:51 UTC, jbm1412 requested changes
![Screenshot (2026)](https://github.com/user-attachments/assets/a0e449f5-63b7-4ad6-9f38-e003fb31500d)

Please fix this issue, check and see before pushing it

2024-12-10 18:25 UTC, jbm1412 approved these changes
![Screenshot (2034)](https://github.com/user-attachments/assets/8e3210a9-8a81-44d6-905c-38d61663684e)

Tested -> Works. Looks Good!

2024-12-11 03:41 UTC, merged