Adding Client Sign-in front-end webpage
Hardhat-Enterprises/website pull request #214
Opened 2024-12-03 10:08 UTC by hiichloee

Have had a call with Arman, we agreed that I'll take on the Sign-in page, and he'll handle the Sign-up page.
We're doing the client sign-in/up pages seperately.

Notice: the current version of the Sign-in page doesn't have the backend connection implemented yet. The form is displayed correctly, but it's not connected to Django for any actual authentication or data handling. It's essentially just a front-end form for now. But it does work for navigation purposes, and the link to the next page is functional.

2024-12-07 07:03 UTC, jbm1412 requested changes
![Screenshot (1985)](https://github.com/user-attachments/assets/1d324923-b965-4154-8d7d-7c646fc9f5a3)

The sign-in interface has turned yellow due to Dark Mode. Please refer to the Team Sign-In Page and follow the colour template to ensure it matches the current website's style.

Additionally, I noticed that in Arman's PR (PR 213), the sign-up process requests a Deakin email, while your sign-in page asks for a personal email. Since this is a collaborative effort, please discuss this discrepancy and make the necessary changes.

2024-12-07 13:35 UTC, hiichloee commented
I’ve made the required updates to the sign-in page as your feedback:

1.Changed the email input field to request a Deakin email instead of a personal email.
2.Updated the label from "Passport" to "Password."

However, regarding the Dark Mode adjustments to align with the Team Sign-In Page's color template, I’m currently unsure how to implement the necessary changes. I don’t have sufficient experience with Dark Mode styling at this stage. While I’m willing to learn and work on it later, I’m unable to address this part right now.

2024-12-07 13:48 UTC, hiichloee commented
Hi team, do i need to send a new pull request for these two?

2024-12-08 05:52 UTC, jbm1412 requested changes

2024-12-08 05:52 UTC, jbm1412 commented on xss_attempts.log
Please delete this file!

2024-12-08 05:52 UTC, jbm1412 commented on xss_attempts.log
Please delete this file as it is overwriting

2024-12-08 06:16 UTC, jbm1412 approved these changes
![Screenshot (1993)](https://github.com/user-attachments/assets/4d473a41-54f3-4b4b-9739-566beb7d5522)

Looks Good!

2024-12-08 07:35 UTC, s-bonnor approved these changes
Looks good, will be merge in a little bit

2024-12-08 07:50 UTC, merged