(feature) malware visualization changes
Hardhat-Enterprises/website pull request #226
Opened 2024-12-06 23:12 UTC by RochanaN

Issue 9: Non-functional Buttons on "Malware Visualization - Join Us" Page. 

Description: Resolved The "Explore Projects" and "Join Us" buttons on the "Malware Visualization - Join Us" page.

2024-12-07 08:54 UTC, jbm1412 requested changes
Page looks good but fix the change

2024-12-07 08:54 UTC, jbm1412 commented on home/templates/pages/malware_visualization/main.html
> +                            <a href="{% url 'smishingdetection_join_us' %}" class="btn btn-primary animate-up-2"
Please remove Smishing Detection Join Us link for Malware Visualization Page

2024-12-08 02:56 UTC, RochanaN commented
@jbm1412 I have removed smishing detection link

2024-12-08 04:42 UTC, s-bonnor commented
This isnt mergeable right now as it seems to be trying to delete a lot of stuff that was added this trimester

2024-12-08 06:01 UTC, RochanaN commented
> This isnt mergeable right now as it seems to be trying to delete a lot of stuff that was added this trimester

can you tell me the files that i have changed?

2024-12-08 06:04 UTC, s-bonnor commented
if you look at the files changed tab you can see that about 20 files are deleted and many more have lines in them deleted

2024-12-08 06:15 UTC, RochanaN commented
i have done 2 changes so far. have you merged the first changes to the main code? (malware visualization ...)

2024-12-08 06:55 UTC, closed without merging