In the contact us page validation every fields.
Hardhat-Enterprises/website pull request #246
Opened 2024-12-08 07:13 UTC by prit-Savani

In the contact us page every fields validation in brief like in the name field numbers are not allowed and in the message is must to write as well as email pettern validation.

2024-12-08 10:52 UTC, jbm1412 requested changes
![Screenshot (2005)](https://github.com/user-attachments/assets/0b3fc051-9e1c-43a5-b1b9-7c7acd9abbde)

Tested -> Works. But fix the things that I've mentioned

2024-12-08 10:52 UTC, jbm1412 commented on home/templates/includes/navigation.html
![Screenshot (2003)](https://github.com/user-attachments/assets/ef30c123-f6b5-49e1-b986-1e0dd023484f)

Fix the dark mode

2024-12-08 10:52 UTC, jbm1412 commented on xss_attempts.log
Delete this file

2024-12-08 12:20 UTC, prit-Savani commented on home/templates/includes/navigation.html
i changed in the HTML code for validation i haven't done anything with the dark mode.
i don't know who is working with dark mode but if no one can fix it i will be happy to do.

2024-12-08 12:26 UTC, prit-Savani commented on xss_attempts.log
done.

2024-12-08 15:18 UTC, jbm1412 commented on home/templates/includes/navigation.html
@prit-Savani please fix the dark mode issue

2024-12-09 13:25 UTC, jbm1412 approved these changes
![Screenshot (2022)](https://github.com/user-attachments/assets/566df737-1263-47d3-8c1e-184b16d5a172)

Tested -> Works, Dark Mode Fixed

2024-12-09 13:26 UTC, jbm1412 requested changes
Please fix the conflicts

2024-12-13 11:22 UTC, jbm1412 commented
This will not be merged because the merge conflict was handled poorly.

2025-04-26 04:23 UTC, closed without merging